version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./users:/var/www/usersproject
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: mysql:5
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: New_password_123

volumes:
  db-data:
    external: false